#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

: "${CHALLENGE_VERSION:=0.1.0}"
: "${CHALLENGE_PORTFILE:=.pison-challenge-port}"

if [[ "$1" =~ -h|--help ]]; then
  echo >&2 "usage: $0"
  echo >&2 ""
  echo >&2 "Runs the Pison challenge jar, creating a portfile to be read by other programs."
  echo >&2 ""
  echo >&2 "Environment Variables:"
  echo >&2 "  CHALLENGE_VERSION:  The version of the challenge jar to run.  "
  echo >&2 "                      Default: 0.1.0"
  echo >&2 "                      Current: ${CHALLENGE_VERSION}"
  echo >&2 "  CHALLENGE_PORTFILE: The portfile name to create.  "
  echo >&2 "                      Default: .pison-challenge-port"
  echo >&2 "                      Current: ${CHALLENGE_PORTFILE}"
  exit 0
fi

jar="challenge-${CHALLENGE_VERSION}.jar"
re="ChallengeServer has started on port ([0-9]+)"

trap "rm -f ${CHALLENGE_PORTFILE}" EXIT

java -jar "$dir/../aux/challenge-${CHALLENGE_VERSION}.jar" |
while read -r line; do
  if [[ "$line" =~ $re ]] ; then
    echo "${BASH_REMATCH[1]}" > "${CHALLENGE_PORTFILE}"
  fi
  echo "$line"
done
